version: "3"
services:
  showandtell-server:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    container_name: showandtell_nodeserver_dev
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: yarn start:dev
